; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32@6.10.0
framework = arduino

board = esp32doit-devkit-v1
board_build.f_cpu = 160000000L # 160 MHz
board_build.flash_mode = qio
board_build.flash_size= 4MB
#board_build.flash_freq=80m

build_flags = #-DCORE_DEBUG_LEVEL=5 # verbose
  -D CONFIG_ASYNC_TCP_MAX_ACK_TIME=5000   // (keep default)
  -D CONFIG_ASYNC_TCP_PRIORITY=10         // (keep default)
  -D CONFIG_ASYNC_TCP_QUEUE_SIZE=64       // (keep default)
  -D CONFIG_ASYNC_TCP_RUNNING_CORE=1      // force async_tcp task to be on same core as Arduino app (default is any core)
  -D CONFIG_ASYNC_TCP_STACK_SIZE=4096     // reduce the stack size (default is 16K)
monitor_speed = 115200

upload_speed = 921600
upload_port = COM3 # /dev/ttyUSB0
#upload_port = 192.168.178.34
#upload_protocol = espota
#upload_flags =
#  --auth=waaatering

lib_deps = 
    https://github.com/marvinroger/async-mqtt-client.git#v0.9.0
    tobiasschuerg/MH-Z CO2 Sensors @ ^1.4.0
    bblanchon/ArduinoJson @ ^7.4.1
    bblanchon/StreamUtils @ ^1.6.3
    adafruit/Adafruit SSD1306 @ ^2.5.6
    plerup/EspSoftwareSerial @ ^8.2.0
    ESP32Async/ESPAsyncWebServer @ ^3.7.6
    knolleary/PubSubClient @ ^2.8.0
    tzapu/WiFiManager @ ^2.0.17
